// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DrawGrids: typeof import('./components/DrawGrids/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Home: typeof import('./components/Home.vue')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    IAkarIconsWater: typeof import('~icons/akar-icons/water')['default']
    IAntDesignHome: typeof import('~icons/ant-design/home')['default']
    IEpCircleClose: typeof import('~icons/ep/circle-close')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpPostcard: typeof import('~icons/ep/postcard')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpUploadFilled: typeof import('~icons/ep/upload-filled')['default']
    IEpWarning: typeof import('~icons/ep/warning')['default']
    IEtPictures: typeof import('~icons/et/pictures')['default']
    IFlatColorIconsKindle: typeof import('~icons/flat-color-icons/kindle')['default']
    IHumbleiconsCoffee: typeof import('~icons/humbleicons/coffee')['default']
    Kindle2Md: typeof import('./components/Kindle2Md/index.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splice: typeof import('./components/Splice.vue')['default']
    Watermark: typeof import('./components/Watermark/index.vue')['default']
  }
}
